FROM apache/age:dev_snapshot_PG16

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*

USER postgres
